### PR TITLE
Change tpose sequence from ragdoll to reference

### PR DESCRIPTION
**Pull request by LUModder**
Affects some custom playermodels (if using the proportions method)

### CODE REVIEW

**Comment by LUModder** [comment]
ragdoll

Compared to

**Comment by CapsAdmin** [comment]
wouldn't this break previous outfits?

**Comment by LUModder** [comment]
How so? It's just changing the sequence used which for most default
playermodels is the same as ragdoll.

**Comment by CapsAdmin** [comment]
nvm i thought this was something entirely different

**Pull request merged**
