### PR TITLE
Some refract shader changes. 

### LINKED ISSUE #703: Material Refract part non-functional.
Big bad. Idk if this has been posted yet but material refract part under experimental doesn't do anything atm apparently, when put on a model it just turns said model invisible and attempts to tick flags for model, etc. or adding textures to it doesn't do anything either, it remains invisible no matter what.

### PR DESCRIPTION
**Pull request by Yagira**
Fixes #703

### CODE REVIEW

**Comment by Earu** [comment]
Don't worry guys im pushing that! /s

**Comment by thegrb93** [comment]
Looks sane, but I don't have any idea what and how the change affects it.

**Comment by thegrb93** [comment]
The defaults are fine. Any explanation as to what the recompute is for?

**Comment by Yagira** [comment]
The material needs to be recomputed for $vertexcolormodulate to actually update. Previously it was set to (1,1,1) which made it invisible and it never changed unless you also changed something else that triggered the recompute. It caused most people to assume that the part didn't work at all. I guess it doesn't really matter anymore after changing it to (0,0,0) since it makes it work by default and there is no need to change $vertexcolormodulate in the editor at all.

**Comment by thegrb93** [comment]
Yeah I see a few other parameters doing the same. Not sure why there's an option for it. Lgtm

**Pull request merged**
