### PR TITLE
Disabled the language ID indicator

### PR DESCRIPTION
**Pull request by zxz41**
It was constantly getting in the way, hiding up to 2-3 characters. I'm supriced nobody did this long ago.

### CODE REVIEW

**Comment by thegrb93** [comment]
What does the language identifier look like? Not exactly sure what this is changing.

**Comment by thegrb93** [comment]
Oh, is this for non-US keyboards I guess?

**Comment by Yagira** [comment]
Yeah, happens if change the keyboard to a different language. 
image

**Review by thegrb93 — APPROVED** [review]
I think the changes look good.

**Pull request merged**
