### PR TITLE
fix pac_sv_hide_outfit_on_death and some other stuff

### PR DESCRIPTION
**Pull request by owltaver**
the outfits hiding, but quickly return due to a little mistake. #825

### CODE REVIEW

**Comment by thegrb93** [comment]
This if/else tree needs rebalancing. The continue will add more confusion/bug potential.

**Comment by thegrb93** [comment]
Nice work finding the cause though.

**Comment by owltaver** [comment]
sure, i'll moved them to dev.

**Comment by thegrb93** [comment]
I moved your commit to a separate branch off of develop and cleaned up the logic. I'm also opening a new PR since this one is attempting to merge to master when it should be trying to merge to develop.

**Pull request closed without merging**
