### PR TITLE
Fix cl error and use global IsValid instead

### PR DESCRIPTION
**Pull request by wrefgtzweve**
Aims to fix
```
addons/fpp/lua/fpp/client/ownability.lua:58: Tried to use a NULL entity!
  1. __newindex - [C]:-1
   2. entGetOwner - addons/fpp/lua/fpp/client/ownability.lua:58
    3. CPPIGetOwner - addons/fpp/lua/fpp/sh_cppi.lua:48
     4. check_owner - addons/pac3/lua/pac3/core/client/owner_name.lua:24
      5. HandleOwnerName - addons/pac3/lua/pac3/core/client/owner_name.lua:136
       6. UpdateOwnerName - addons/pac3/lua/pac3/core/client/parts/group.lua:94
        7. fn - addons/pac3/lua/pac3/core/client/part_pool.lua:435
         8. unknown - addons/ulib/lua/ulib/shared/hook.lua:109
```
Which causes CPPI addons to error as a NULL entity is being passed into it's functions.
This pr moves the checks into a block where the owner is valid.

This pr also converts :IsValid() to IsValid() to catch future possible errors as the meta table function doesn't work on nil values.

### CODE REVIEW

**Comment by thegrb93** [comment]
The error isn't complaining about nil so I would prefer the IsValid checks be reverted.

**Comment by wrefgtzweve** [comment]
Yeah, the conversion isn't to fix this specific error but any possible errors in the future.
As the wiki puts it:
image
And we can't know for sure that all of these are actual entities or nil values.

There's no real benefit to use :IsValid() over IsValid() yet there are benefits to do the reverse.

Examples of :IsValid() causing issues in other projects:
https://github.com/thegrb93/StarfallEx/issues/1288
https://github.com/thegrb93/StarfallEx/issues/1207

**Comment by thegrb93** [comment]
`:IsValid()` is preferred when the var won't be nil because it has lower performance cost.

**Comment by wrefgtzweve** [comment]
That's why i localize it at the top, there's pretty much no significant performance difference
Some quick test i ran:

SV:
```
ent:IsValid() Total: 0.066698999999062 seconds. Average: 6.6698999999062e-08 seconds.
ent:IsValid() Total: 0.062645999998495 seconds. Average: 6.2645999998495e-08 seconds.
ent:IsValid() Total: 0.062885999999708 seconds. Average: 6.2885999999708e-08 seconds.
ent:IsValid() Total: 0.062466999999742 seconds. Average: 6.2466999999742e-08 seconds.
ent:IsValid() Total: 0.062668999999005 seconds. Average: 6.2668999999005e-08 seconds.
ent:IsValid() Total: 0.062595999999758 seconds. Average: 6.2595999999758e-08 seconds.
ent:IsValid() Total: 0.062657000002218 seconds. Average: 6.2657000002218e-08 seconds.
ent:IsValid() Total: 0.062874000002921 seconds. Average: 6.2874000002921e-08 seconds.
ent:IsValid() Total: 0.062583999999333 seconds. Average: 6.2583999999333e-08 seconds.
ent:IsValid() Total: 0.062556000000768 seconds. Average: 6.2556000000768e-08 seconds.
IsValid(ent) Total: 0.062722000002395 seconds. Average: 6.2722000002395e-08 seconds.
IsValid(ent) Total: 0.061952000000019 seconds. Average: 6.1952000000019e-08 seconds.
IsValid(ent) Total: 0.062442999998893 seconds. Average: 6.2442999998893e-08 seconds.
IsValid(ent) Total: 0.062276999997266 seconds. Average: 6.2276999997266e-08 seconds.
IsValid(ent) Total: 0.062642000000778 seconds. Average: 6.2642000000778e-08 seconds.
IsValid(ent) Total: 0.062010999998165 seconds. Average: 6.2010999998165e-08 seconds.
IsValid(ent) Total: 0.062851999999111 seconds. Average: 6.2851999999111e-08 seconds.
IsValid(ent) Total: 0.0625629999995 seconds. Average: 6.25629999995e-08 seconds.
IsValid(ent) Total: 0.062616999999591 seconds. Average: 6.2616999999591e-08 seconds.
IsValid(ent) Total: 0.061954000000696 seconds. Average: 6.1954000000696e-08 seconds.
```

CL:
```
ent:IsValid() Total: 0.0600929000002 seconds. Average: 6.00929000002e-08 seconds.
ent:IsValid() Total: 0.060093699999925 seconds. Average: 6.0093699999925e-08 seconds.
ent:IsValid() Total: 0.060417899999266 seconds. Average: 6.0417899999266e-08 seconds.
ent:IsValid() Total: 0.05972279999969 seconds. Average: 5.972279999969e-08 seconds.
ent:IsValid() Total: 0.059941500000605 seconds. Average: 5.9941500000605e-08 seconds.
ent:IsValid() Total: 0.060408300000745 seconds. Average: 6.0408300000745e-08 seconds.
ent:IsValid() Total: 0.059556600000178 seconds. Average: 5.9556600000178e-08 seconds.
ent:IsValid() Total: 0.059410699999717 seconds. Average: 5.9410699999717e-08 seconds.
ent:IsValid() Total: 0.059327799999664 seconds. Average: 5.9327799999664e-08 seconds.
ent:IsValid() Total: 0.059796300000016 seconds. Average: 5.9796300000016e-08 seconds.
IsValid(ent) Total: 0.055769499999769 seconds. Average: 5.5769499999769e-08 seconds.
IsValid(ent) Total: 0.055455900000197 seconds. Average: 5.5455900000197e-08 seconds.
IsValid(ent) Total: 0.056095899999491 seconds. Average: 5.6095899999491e-08 seconds.
IsValid(ent) Total: 0.056027999999969 seconds. Average: 5.6027999999969e-08 seconds.
IsValid(ent) Total: 0.056515899999795 seconds. Average: 5.6515899999795e-08 seconds.
IsValid(ent) Total: 0.056074800000715 seconds. Average: 5.6074800000715e-08 seconds.
IsValid(ent) Total: 0.056192200000623 seconds. Average: 5.6192200000623e-08 seconds.
IsValid(ent) Total: 0.057141799999954 seconds. Average: 5.7141799999954e-08 seconds.
IsValid(ent) Total: 0.056129100000362 seconds. Average: 5.6129100000362e-08 seconds.
IsValid(ent) Total: 0.05683769999996 seconds. Average: 5.683769999996e-08 seconds.
```

Code:
```lua
local SysTime = SysTime
local ent = Entity( 2 )
local IsValid = IsValid
local count = 1000000

for i = 1, 10 do
	local StartTime = SysTime()

	for i = 1, count do
		IsValid( ent )
	end
	
	local EndTime = SysTime()
	local TotalTime = EndTime - StartTime
	local AverageTime = TotalTime / count
	
	print("ent:IsValid() Total: " .. TotalTime .. " seconds. Average: " .. AverageTime .. " seconds.")
end

for i = 1, 10 do
	local StartTime = SysTime()

	for i = 1, count do
		ent:IsValid()
	end
	
	local EndTime = SysTime()
	local TotalTime = EndTime - StartTime
	local AverageTime = TotalTime / count
	
	print("IsValid(ent) Total: " .. TotalTime .. " seconds. Average: " .. AverageTime .. " seconds.")
end
```

**Comment by wrefgtzweve** [comment]
The peformance difference is pretty much neglectable if IsValid is localized
SV:
```
IsValid(ent) Total: 0.067231000000902 seconds. Average: 6.7231000000902e-08 seconds.
IsValid(ent) Total: 0.059456999999384 seconds. Average: 5.9456999999384e-08 seconds.
IsValid(ent) Total: 0.059419000001071 seconds. Average: 5.9419000001071e-08 seconds.
IsValid(ent) Total: 0.059427000000142 seconds. Average: 5.9427000000142e-08 seconds.
IsValid(ent) Total: 0.060604999998759 seconds. Average: 6.0604999998759e-08 seconds.
IsValid(ent) Total: 0.059386999997514 seconds. Average: 5.9386999997514e-08 seconds.
IsValid(ent) Total: 0.060545000000275 seconds. Average: 6.0545000000275e-08 seconds.
IsValid(ent) Total: 0.059519000002183 seconds. Average: 5.9519000002183e-08 seconds.
IsValid(ent) Total: 0.059484000001248 seconds. Average: 5.9484000001248e-08 seconds.
IsValid(ent) Total: 0.05998499999987 seconds. Average: 5.998499999987e-08 seconds.
ent:IsValid() Total: 0.059582000001683 seconds. Average: 5.9582000001683e-08 seconds.
ent:IsValid() Total: 0.059137000000192 seconds. Average: 5.9137000000192e-08 seconds.
ent:IsValid() Total: 0.058841999998549 seconds. Average: 5.8841999998549e-08 seconds.
ent:IsValid() Total: 0.059160000000702 seconds. Average: 5.9160000000702e-08 seconds.
ent:IsValid() Total: 0.059377999998105 seconds. Average: 5.9377999998105e-08 seconds.
ent:IsValid() Total: 0.058967000000848 seconds. Average: 5.8967000000848e-08 seconds.
ent:IsValid() Total: 0.059378999998444 seconds. Average: 5.9378999998444e-08 seconds.
ent:IsValid() Total: 0.059537000001001 seconds. Average: 5.9537000001001e-08 seconds.
ent:IsValid() Total: 0.060131999998703 seconds. Average: 6.0131999998703e-08 seconds.
ent:IsValid() Total: 0.059430999997858 seconds. Average: 5.9430999997858e-08 seconds.
``` 

Code:
```lua
local SysTime = SysTime
local ent = Entity( 2 )
local IsValid = IsValid
local count = 1000000

for i = 1, 10 do
	local StartTime = SysTime()

	for i = 1, count do
		IsValid( ent )
	end
	
	local EndTime = SysTime()
	local TotalTime = EndTime - StartTime
	local AverageTime = TotalTime / count
	
	print("IsValid(ent) Total: " .. TotalTime .. " seconds. Average: " .. AverageTime .. " seconds.")
end

for i = 1, 10 do
	local StartTime = SysTime()

	for i = 1, count do
		ent:IsValid()
	end
	
	local EndTime = SysTime()
	local TotalTime = EndTime - StartTime
	local AverageTime = TotalTime / count
	
	print("ent:IsValid() Total: " .. TotalTime .. " seconds. Average: " .. AverageTime .. " seconds.")
end
```

**Comment by thegrb93** [comment]
Overhead can compound and add up. Using global IsValid can imply that the variable may be nil which is also unwanted in many cases.

**Comment by wrefgtzweve** [comment]
Im worried that this fix will just shove the error further rather than actually fixing it, because this is going to return `NULL` which might causes issues down the line too

**Comment by thegrb93** [comment]
Looks like the callers of this function even have ` or NULL` on them so it'd definitely intended.

**Pull request merged**
