### PR TITLE
Fix text getting cut off

### PR DESCRIPTION
**Pull request by FarukGamer**
This should fix text which got cutoff.

### CODE REVIEW

**Comment by thegrb93** [comment]
I remember surface.DisableClipping( false ) causing issues in starfall. I think true is the default.

**Comment by DBotThePony** [comment]
text should be really long for this to be an issue

**Comment by CapsAdmin** [comment]
surface.DisableClipping is for clipping when text and other things goes outside of the viewport. It makes sense to disable this when doing things in 3d.  Maybe at a higher level though, and not per text part?

It's a new function and I can't recall ever having issues with this since after it was introduced. Maybe some optimization update was the reason.

**Comment by thegrb93** [comment]
Here's the related starfall issue @DBotThePony @CapsAdmin @FarukGamer https://github.com/thegrb93/StarfallEx/issues/747

**Comment by thegrb93** [comment]
This was the fix. https://github.com/thegrb93/StarfallEx/commit/641e1c96279ac04cf3be9aafc7e17e2e5ca856aa

I think the issue is other addons set it to true and then back to false without realizing it's supposed to stay true.

**Pull request merged**
