### PR TITLE
replace some type with is*

### PR DESCRIPTION
**Pull request by FarukGamer**
C `is*` funcs are faster then `type`, since a string doesn't have to be pushed to Lua, and the code doesn't have to return to C for the string comparison.

### CODE REVIEW

**Comment by CapsAdmin** [comment]
Do you see a performance benefit from doing this?

**Comment by CapsAdmin** [comment]
I prefer using type as it's a standard lua function. But I can get onboard with using isangle, isvector, etc for non standard lua types.

The exception I make is for performance, but I shouldn't be comparing types in performance sensitive code anyway. Looking at the code that's changed, I mostly see changes in code that is not being called often.

**Comment by thegrb93** [comment]
I think jit would normally optimize them (if garry hadn't botched the type function) so these are the optimal way to do it in gmod.

**Comment by thegrb93** [comment]
That said, that may not always be the case if https://github.com/Facepunch/garrysmod-issues/issues/4100 ever gets resolved.

**Comment by thegrb93** [comment]
We could git revert if things change though.

**Comment by thegrb93** [comment]
Just reviewed the changes and they look one to one so it's just a matter of whether we want the change.

**Comment by FarukGamer** [comment]
@CapsAdmin Just take a look here. Evetho the link refers to a ulib pull request. Somebody did benchmark it.

https://github.com/TeamUlysses/ulib/pull/58#issuecomment-518730448

**Comment by CapsAdmin** [comment]
I believe you when you say the function is faster, but when it comes to performance in PAC3 you should be comparing performance for when an outfit is being rendered.

If you want an even faster type and is* function, see 

https://github.com/PAC3-Server/notagain/blob/master/lua/notagain/optimizations/preinit/luaify.lua#L6-L76

You can apply this globally and all addons will benefit from it without having to resort to writing gmod specific lua.

**Comment by FarukGamer** [comment]
It ment to be just some micro optimisation. That it will improve the **runtime performance** . But do not stick to my words. You may know better, I just wanted to submit a possible improvement.

**Comment by thegrb93** [comment]
No sense in wasting perfectly good work. Just poke Caps until he merges it.

**Comment by thegrb93** [comment]
> https://github.com/PAC3-Server/notagain/blob/master/lua/notagain/optimizations/preinit/luaify.lua#L6-L76

This is disgusting. I'm going to try it out

**Comment by FarukGamer** [comment]
@thegrb93 If your tests for that brings nothing good, then will open it back.

**Comment by thegrb93** [comment]
I think it ought to be merged either way, but ya I'll see if it helps starfall at all

**Comment by thegrb93** [comment]
Seems jit.off() still faster than that optimization

**Pull request closed without merging**
