### PR TITLE
Pull CallHook function fixes into master

### PR DESCRIPTION
**Pull request by brandonsturgeon**
Hi,

I'm not familiar with the project's branching strategy, let me know if there's a better way to do this.

I'm proposing pulling my `CallHook` fixes from `develop` into `master`.
I believe these are very low-risk, high-value changes.

What do you all think?

### CODE REVIEW

**Comment by thegrb93** [comment]
I'd like to pull everything to workshop, but I need confirmation that develop branch is decently stable right now.

**Comment by DBotThePony** [comment]
> I'd like to pull everything to workshop, but I need confirmation that develop branch is decently *stable* right now.

None at all.

**Comment by thegrb93** [comment]
You have to find some stable point to release sometime or the master/workshop will never update.

**Comment by thegrb93** [comment]
Just merged develop to master

**Pull request closed without merging**
