### PR TITLE
Patch refactor webaudio

### PR DESCRIPTION
**Pull request by suchipi**
Disclaimer: All conflict resolution was done at 2AM and I'm only human. 

@notcake should probably review this one to ensure conflict resolution was properly handled.

### CODE REVIEW

**Comment by suchipi** [comment]
I lied, there wasn't any conflict resolution in this one. You still might want to check to make sure I didn't miss a commit, though, notcake

**Comment by suchipi** [comment]
conflicts resolved

**Comment by CapsAdmin** [comment]
still in conflict

**Comment by CapsAdmin** [comment]
merged outside of github

**Pull request merged**
