### PR TITLE
Fix followpart using euler angle addition for following bones.

### PR DESCRIPTION
**Pull request by thegrb93**
This is going to break a lot of pacs that use followpart but they were technically already broken. I'd make sure this is the behavior we want before merging though.

Fixes https://github.com/CapsAdmin/pac3/issues/571

### CODE REVIEW

**Comment by Techbot121** [comment]
how about deprecating the old one but still make it functional? I think the scale changes were done that way too.

**Comment by CapsAdmin** [comment]
Yes, just make this a new property and deprecate the old one.

We can also think about making "bone2" if needed as well

**Comment by thegrb93** [comment]
What should the new field be called? FollowPart2, FollowPartNew, FollowPartFixed, FollowPartMatrix?

**Comment by CapsAdmin** [comment]
Can you make a new part called bone2.lua with the fixes and put it under the pac4 submenu?

There are other things I want to change about bones I think that might break everything.

**Comment by thegrb93** [comment]
All right

**Comment by thegrb93** [comment]
Should be ready

**Pull request merged**
