### PR TITLE
use full material path instead of name when needed

### LINKED ISSUE #1146: MDL downloads does not seek proper textures despite existing on -fastbuild MDLs
- [Model ZIP](https://iastg.s3.ap.cloud-object-storage.appdomain.cloud/stg_1928032180128730.zip).

PAC3 does not know where to look for textures despite existing within the ZIP when the MDL is compiled using -fastbuild.

image

### PR DESCRIPTION
**Pull request by Yagira**
fixes #1146

### CODE REVIEW

**Comment by thegrb93** [comment]
Won't this possible cause an issue if there are two materials of same name but in different folders?

**Comment by Yagira** [comment]
Right, this change should handle it as long as you keep the original folder structure when making the zip. It's probably a very rare case anyway.

**Comment by thegrb93** [comment]
I think the rest of the code looks ok. I'm still nervous about matching the filename despite different directory though.

**Comment by Yagira** [comment]
> Why's the `v.file_path:match(mat)` there? This seems strange to me.

Both this and `v.file_name == mat:match(".+/(.+)")` is for cases where someone changed the folder structure, so if there's more folders in the path or there's no `materials` folder or even no folders at all. If the original path doesn't exist then try to match a part of it or the name. 

It's pretty much an attempt to catch things that could be wrong and fix them.

**Comment by thegrb93** [comment]
Oh I see. Can you change that to `string.find(mat, v.file_name, 1, true)`?

**Comment by Yagira** [comment]
This should be fine. Also here is a model zipped in three different ways that I used for testing if you wanna check it out yourself.

[original](https://h.yag.ovh/f/nbisarin.zip)
[additional folder](https://h.yag.ovh/f/folder.zip)
[no folders](https://h.yag.ovh/f/rush1.zip)

**Comment by thegrb93** [comment]
The second match was fine. Could also be `v.file_name==string.GetFileFromFilename(mat)`

**Comment by thegrb93** [comment]
I'll take a look at your examples in a bit

**Comment by thegrb93** [comment]
Can you explain what causes each of your examples? Where do these cases arise? I looked in each .mdl and they are exactly the same so I'm thinking something with the directory structure needs to be improved.

**Comment by Yagira** [comment]
The examples are just the common ways that people make their mdl .zips. They were just to show that even 'broken' zips will still work in PAC. You can load any of the example links in game and you will end up with a proper .gma no matter which one you use.

**Comment by thegrb93** [comment]
Ah so this is just a workaround for #1146 . I'm still very nervous about this change. For example, you can have a model with different clothes bodygroups with materials of the same name in different folders. It'd be a good idea to be sure this doesn't break those.

**Pull request merged**
