### PR TITLE
write tangent userdata to urlobj meshes for bumpmaps

### PR DESCRIPTION
**Pull request by willox**
`IMesh:BuildFromTriangles` in GMod's dev branch can write userdata to mesh vertices now. If you want bumpmaps to work, put the tangent data in there.

This is more of an example than a pull-request and doesn't do anything fancy like yielding the coroutine. Important bit is line 617.

### CODE REVIEW

**Comment by thegrb93** [comment]
Nice

**Comment by roboderpy** [comment]
Is this safe to merge to develop branch before develop release in gmod?

**Comment by Kefta** [comment]
Could these changes be added to the wiki?

**Comment by thegrb93** [comment]
@roboderpy yeah it's just adding an unused key to the mesh table.

**Pull request merged**
