### PR TITLE
Easing Styles for individual frames in custom anims

### PR DESCRIPTION
**Pull request by ZH-Hristov**
Allows individual frames in linearly-interpolated custom anims to use easing styles borrowed from 
**lua/includes/extensions/math/ease.lua**
I'm not sure how to add support to set these in the editor, so they have to be set in the json of the anim in the FrameData right now.

[A vid showing a simple 3 frame animation with some easing styles applied to it](https://streamable.com/1dukia)
And here's the anim's JSON:
```
{
	"Type": "gesture",
	"FrameData": [
		{
			"FrameRate": 50.0,
			"BoneInfo": {
				"ValveBiped.Bip01_Pelvis": {
					"RU": 0.0,
					"MU": 0.0,
					"MF": 0.0,
					"MR": 0.0,
					"RR": 0.0,
					"RF": 0.0
				}
			}
		},
		{
			"FrameRate": 1.0,
			"EaseStyle": "InOutElastic",
			"BoneInfo": {
				"ValveBiped.Bip01_Pelvis": {
					"RU": 0.0,
					"MU": 51.400001525878909,
					"RR": 0.0,
					"MR": 0.0,
					"MF": 0.0,
					"RF": 0.0
				}
			}
		},
		{
			"FrameRate": 1.0,
			"EaseStyle": "OutBounce",
			"BoneInfo": {
				"ValveBiped.Bip01_Pelvis": {
					"RU": 0.0,
					"MU": 0.0,
					"MF": 0.0,
					"MR": 0.0,
					"RR": 0.0,
					"RF": 0.0
				}
			}
		}
	],
	"Interpolation": "linear"
}
```

### CODE REVIEW

**Comment by thegrb93** [comment]
Looks good. I'll take a closer look and test it out soon

**Comment by thegrb93** [comment]
All the code looks great. Thanks

**Comment by ZH-Hristov** [comment]
I wanna look into adding a way to set these in-editor at some point, but kinda busy with work atm. Any idea how difficult/tedious that would be?

**Comment by thegrb93** [comment]
I don't really know the animation editor very well at all unfortunately. Most editor things in pac3 are pretty easy so it might not be too hard.

**Pull request merged**
