### PR TITLE
obsfucate part_pool.lua at runtime

### PR DESCRIPTION
**Pull request by CapsAdmin**
this obfuscates and randomizes upvalues

### CODE REVIEW

**Comment by CapsAdmin** [comment]
@Python1320 @thegrb93 @Kamshak

**Comment by thegrb93** [comment]
ack, this upsets my server's anticheat. I'll see if I can make an exception or something

**Comment by CapsAdmin** [comment]
Good point about the uid thing. I do prepend _ in front of it in all places except one where I forgot, but it should probably be part of gen_uid and then the function being renamed to generate_identifier or something.

Is it being flagged because of runstring?

**Comment by thegrb93** [comment]
yea hooks added in code that has not been AddCSLuaFile'd or something like that get flagged as cheater's hooks.

**Comment by thegrb93** [comment]
I can just add an exception to it.

**Pull request merged**
