### PR TITLE
[...] button fix

### PR DESCRIPTION
**Pull request by LUModder**
After recent GMod update, the buttons for selecting and stuff broke. Adding a 1 tick timer fixes this.

### CODE REVIEW

**Comment by Python1320** [comment]
Until we figure out what actually broke this shall do.

**Comment by cooolguy2** [comment]
plz dont slap but where the zip download

**Comment by LUModder** [comment]
@cooolguy2 It's right here

**Comment by CapsAdmin** [comment]
I managed to push the changes to workshop

**Comment by cooolguy2** [comment]
thx LU and Caps now i can finaly work on my new pac

**Comment by CapsAdmin** [comment]
are you sure this works? people keep saying its broken and i pushed this fix to workshop (unless that didn't work somehow)

**Comment by LUModder** [comment]
It's been working on Meta fine so I don't know why it wouldn't work elsewhere.

**Comment by CapsAdmin** [comment]
metastruct fucks with everything so its generally not a good place to test
things like this. but python1320 just confirmed it was working anyway

**Pull request merged**
