### PR TITLE
better typecheck

### PR DESCRIPTION
**Pull request by owltaver**
Just noticed that forceobj does not work on SetModel in most cases, so this is not only [convertation issue](https://github.com/CapsAdmin/pac3/issues/1066). Guess because meta vars is not full loaded at that moment. Anyway there is a some better way to do typechecks and make it automated.

### CODE REVIEW

**Comment by CapsAdmin** [comment]
Looks good. The only thing I'm worried about is potential breaking so I'd like to test some cases myself first.

**Comment by CapsAdmin** [comment]
When using onedrive the HEAD response is 
```Cache-Control	=	no-cache, no-store
Content-Length	=	0
Date	=	Mon, 21 Jun 2021 22:26:55 GMT
Expires	=	-1
Pragma	=	no-cache
Set-Cookie	=	E=P:Qv00rQM12Yg=:5geWaawr81fpzUZe4cPKaTdnYLnVpspnAYZdHPBW5vM=:F; domain=.live.com; path=/
```
So Content-Type is missing. I think there should be a fallback of some sort

**Comment by thegrb93** [comment]
What was the response code there? 204?

**Comment by CapsAdmin** [comment]
Right, it's actually 404. Probably because onedrive doesn't support HEAD requests.

I'd post the url but there's a scary authKey query param in it and it's not my url. 😅

**Pull request merged**
