### PR TITLE
for what i've seen this works, and prevents error on part init

### PR DESCRIPTION
**Pull request by Earu**

### CODE REVIEW

**Comment by CapsAdmin** [comment]
What's the error? With the way Lua works this shouldn't make a difference.

**Comment by Earu** [comment]
@CapsAdmin now it should be fine, and not error if the part is getting initalized before the client has fully initialized.

**Comment by Earu** [comment]
Agreement that fix needs to be global and not ductape

**Comment by CapsAdmin** [comment]
but I'm lazy atm so it's better than nothing maybe

**Pull request merged**
