### PR TITLE
boneanimlib a nil value

### PR DESCRIPTION
**Pull request by Heyter**

### CODE REVIEW

**Comment by thegrb93** [comment]
What's boneanimlib?

**Comment by DBotThePony** [comment]
boneanimlib is (still?) used for Lua based animations

**Comment by Heyter** [comment]
I don't know what it is, just fixed the error.

**Comment by thegrb93** [comment]
I'm guessing this option is there to counteract some 3rd party library. This change looks good.

**Comment by thegrb93** [comment]
I think the option text should be changed to 'Stop all boneanimlib animations', but idk if that's better or worse.

**Comment by Techbot121** [comment]
Just for future reference:
[boneanim lib was replaced by "animations.lua" in libraries.](https://github.com/CapsAdmin/pac3/commit/237cacaad5d132663cfa0c76631b84addbf960d9) 
[Originally it was made by jetboom](https://github.com/JetBoom/animationsapi) and I guess caps modified it and changed the name.

**Comment by thegrb93** [comment]
Thanks. I've corrected it.

**Pull request merged**
