### PR TITLE
fix default pac part icon

### PR DESCRIPTION
**Pull request by suchipi**
Disclaimer: All conflict resolution was done at 2AM and I'm only human.

### CODE REVIEW

**Comment by CapsAdmin** [comment]
Both icons exist and from what I understand the gui/* silkicons are deprecated in favor of icon16/*

What's the purpose of doing this?

**Comment by suchipi** [comment]
I don't think the old path works at all anymore; before I made this change, parts that weren't in the tree would just display with a blank icon.

The only place I ever end up seeing it though is when developing parts in-game.

**Comment by suchipi** [comment]
conflict (!?) resolved

**Comment by suchipi** [comment]
Would you merge this if I bothered to rebase it?

**Comment by CapsAdmin** [comment]
Yes. For some reason I read the merge the other way around (you changing it from "icon16/plugin.png" to "gui/icons/plugin)

**Comment by suchipi** [comment]
I'm gonna just make a new branch and PR off of suchipi/pac3 because I don't know what's up with Metastruct/pac3 anymore

**Pull request closed without merging**
