### PR TITLE
Add FCVAR_SERVER_CAN_EXECUTE to server cvars

### LINKED ISSUE #270: All PACs Disappear When the Owner dies in Multiplayer
My issue is as the title states, for some reason all PACs will disappear upon death of the owner. I know this is clientside as I heard my death sound in another person's mic while they were talking, but I could not see/hear my PAC and death sound when I died. This is incredibly frustrating and I have not been able to find a fix for it, so I hope to find it here.

EXTRA INFO:
Yes, I have gone into singleplayer and changed pac_sv_hide_outfit_on_death to 0, but it seems to reset to 1 when I join any server that has PAC3 enabled despite the server not having that option set as such.
My PAC does not disappear when I try to test this in singleplayer, so this is definitely something to do with multiplayer.
Another thing that I forgot to add in my sleepless state when I made this post was the fact that, in singleplayer, pac_sv_hide_outfit_on_death is already set to 0, so I'm not sure what it is about multiplayer that is doing this.

### PR DESCRIPTION
**Pull request by LUModder**
Should fix #270

### CODE REVIEW

**Comment by 00875** [comment]
Lua convar never gets sended if it is have it's default value

**Comment by LUModder** [comment]
okay mr "im smart and im a tryhard trying to make a better sit anywhere", you fix it then

**Comment by Noiwex** [comment]
You're super toxic, I'm wondering how you're still not banned there.

**Comment by LUModder** [comment]
@Noiwex You're not any better.

**Comment by LUModder** [comment]
Also apperently Willox fixed the old issue in dev branch

**Pull request closed without merging**
