### PR TITLE
Entity fix

### LINKED ISSUE #1098: pac_restart causes entity desync
If you use `pac_restart` while SOMEONE ELSE is using the entity part they will get stuck in place or start lagging/teleporting/whatever on your end. This is not a new problem, it's been a thing for a while. It persists until you restart/rejoin the server. 

Video: https://drive.google.com/file/d/1k2OaKZE5T8OLoc3hHWKyBJW9bUPylgER/view?usp=sharing

If you use `pac_restart` while YOU are using the entity part you will end up in that weird state with broken animations or something. Also persists until restart (?).

Video: https://drive.google.com/file/d/1LzYuXeZ3EyRMkdGJhMZKSMkAeWK1X_sI/view?usp=sharing

As a bonus this breaks the model_name event even since apparently `:GetModel()` returns the wrong model (???) after a restart.

Model used: https://wiki.pac3.info/_media/tutorial/mdl/animegirl.zip

### PR DESCRIPTION
**Pull request by Yagira**
Should fix #1098 and #1089 as well as random error models and broken ragdolls. Hopefully it doesn't break anything.

### CODE REVIEW

**Comment by Techbot121** [comment]
I'm currently testing this on metastruct, works fine so far, only downside of this you have to clear the pac3_cache of both **local and server**

**Comment by thegrb93** [comment]
What's wrong if you don't clear the cache?

**Comment by Yagira** [comment]
We thought that maybe it was cache related because some people kept seeing errors but that doesn't really make sense because the ids changed anyway.

I think that the actual problem is the way pac works. The server got restarted and some people joined to try the new version, they wore their outfits etc. Then some more people joined and that is where the problem starts, because you need to be on the server when someone wears the outfit in order to see it (this affects outfits in general not just the entity). If you don't see the outfit you never download the model so you just end up with an error. To fix it you have to either wait for people to re-wear or just ask them to do so which is kinda silly.
 
Maybe outfits should auto wear every X minutes or players should somehow receive them when joining the game / be able to request them on their own.

**Comment by Techbot121** [comment]
what you're looking for is here 
https://github.com/CapsAdmin/pac3/blob/develop/lua/pac3/core/shared/entity_mutator.lua#L307-L317

This should send the players the entity mutators when they first move, but I guess it doesn't?
I'm just speculating since I didn't actually try it ingame yet.

**Comment by thegrb93** [comment]
Seems to have caused https://github.com/CapsAdmin/pac3/issues/1097 . Could you rework your fixes and resubmit? I can provide a reproduction outfit if needed.

**Pull request merged**
