### PR TITLE
add voice_volume_scale

### PR DESCRIPTION
**Pull request by 0x098**

### CODE REVIEW

**Comment by thegrb93** [comment]
Hows this differ from voice_volume? Would it be better if voice_volume multiplied with the scale itself instead?

**Comment by 0x098** [comment]
> Hows this differ from voice_volume? Would it be better if voice_volume multiplied with the scale itself instead?

there could be use cases for not having it already scaled and vice versa

**Comment by thegrb93** [comment]
Ok I guess. Can you fix the conflict?

**Comment by 0x098** [comment]
idk how to use github so i guess not

**Pull request merged**
